# -*- coding: utf-8 -*-
"""a1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17AYW5zN6l3nOYg4iToKiTvm2QkC00Keg

### Natural Language Processing: Assignment 1

##### This is demo program which give you idea about how to start  your assignment.
"""

## for installing UrduHack
!pip install urduhack[tf]

"""##### Reading File"""

import csv

with open('sent-test.txt', 'rt', encoding="utf-8") as f:
    reader = csv.reader(f)
    passage = list(reader)
f.close()
text = passage[0][0]
print(text)

"""##### Segmentation using UrduHack"""

import urduhack
from urduhack.tokenization import sentence_tokenizer


sentences = sentence_tokenizer(text)
sentences

len(sentences)

"""#### Reading Segmented File"""

with open('sent-segmented.txt', 'rt', encoding="utf-8") as f:
    reader = csv.reader(f)
    segmented = list(reader)
f.close()

seg_text = segmented[0][0]
sents = seg_text.split('۔')
len(sents)

w_list = word_tokenizer(seg_text)

w_list[0]

"""##### Your Sentence Segmentation Code"""



"""#### Compute Accuracy and Print Results"""

